version: "3.9"
services:
  api:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    ports:
    - 5000:5000
  db: 
    image: library/mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: jokes
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10